---
vagrant_box: geerlingguy/ubuntu1404

vagrant_hostname: solrvm.dev
vagrant_machine_name: solrvm

vagrant_ip: 192.168.56.107
vagrant_public_ip: ""

# Memory and CPU to use for this VM.
vagrant_memory: 2048
vagrant_cpus: 2

solr_port: 8983

# Minimum required versions.
solrvm_vagrant_version_min: '1.8.5'
solrvm_ansible_version_min: '2.1'

# Search API (solr)
search_api_solr_version: '7.x-1.11'

# geerlingguy.solr overrides
# @see https://bitbucket.org/phase2tech/arsenal/src/219c5eee800d684603dbe65696a0da46cb1eb8ee/dockerfiles/solr4/Dockerfile?at=develop&fileviewer=file-view-default
solr_base_version: '4.x'
solr_version: '4.10.4'
solr_file: "solr-{{ solr_version }}"

# geerlingguy.firewall overrides
firewall_allowed_tcp_ports:
  - "22"
  - "25"
  - "80"
  - "443"
  - "8983"

force_ansible_local: yes
