---
# Use ansible galaxy for local install.
# ansible-galaxy install geerlingguy.solr
# ansible-galaxy install geerlingguy.java

- hosts: all
  become: yes

  vars_files:
    - ../default.config.yml

  pre_tasks:
    - name: Verify Ansible meets the VM's version requirements.
      assert:
        that: "ansible_version.full | version_compare(solrvm_ansible_version_min, '>=')"
        msg: >
          "You must update Ansible to at least {{ solrvm_ansible_version_min }} to use this version of the VM."

    - name: Define config_dir.
      set_fact:
        config_dir: "{{ playbook_dir }}/.."
      when: config_dir is not defined

    - include_vars: "{{ item }}"
      with_fileglob:
        - "{{ config_dir }}/config.yml"
  roles:
    - geerlingguy.java
    - geerlingguy.solr
    - geerlingguy.firewall
    - scottalan.searchapisolr

  tasks: []

